./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
./submitJob.sh ls -l &
